spring:
  application:
    # 模块名称
    name: shop

  datasource:
    url: jdbc:mysql://120.27.248.163:3306/mysql_dev?serverTimezone=GMT
    username: root
    password: QWEr105521+
    driver-class-name: com.mysql.cj.jdbc.Driver


